package com.nenotv.player.storage;
import android.content.*; import com.nenotv.player.model.MediaEntry; import org.json.*; import java.util.*;
public class LibraryStore {
    private final SharedPreferences p; private final CryptoBox crypto;
    public final String viewerId;
    public LibraryStore(Context c){viewerId=new HouseholdProfileStore(c).activeId();p=c.getSharedPreferences(HouseholdProfileStore.libraryName(viewerId),Context.MODE_PRIVATE);crypto=new CryptoBox();LibraryKeyMigration.run(p);}
    public boolean isFavorite(MediaEntry e){return e!=null&&p.getStringSet("favorites",Collections.emptySet()).contains(StoredMediaKey.of(e));}
    public void toggleFavorite(MediaEntry e){Set<String>s=new HashSet<>(p.getStringSet("favorites",Collections.emptySet()));if(!s.add(StoredMediaKey.of(e)))s.remove(StoredMediaKey.of(e));p.edit().putStringSet("favorites",s).apply();cache(e);noteInterest(e);}
    public void recent(MediaEntry e){cache(e);noteInterest(e);List<String>r=new ArrayList<>();try{JSONArray a=new JSONArray(p.getString("recent","[]"));for(int i=0;i<a.length();i++)if(!a.optString(i).equals(StoredMediaKey.of(e)))r.add(a.optString(i));}catch(Exception ignored){}r.add(0,StoredMediaKey.of(e));if(r.size()>80)r=r.subList(0,80);p.edit().putString("recent",new JSONArray(r).toString()).apply();}
    public void noteInterest(MediaEntry e){if(e==null||e.categoryId==null||e.categoryId.isEmpty())return;String type="episode".equals(e.type)?"series":e.type;String k="interest:"+type+":"+e.categoryId;int n=Math.min(1000,p.getInt(k,0)+1);p.edit().putInt(k,n).apply();cache(e);}
    public String preferredCategoryId(String type){Map<String,Integer>m=new HashMap<>();String prefix="interest:"+type+":";for(Map.Entry<String,?>x:p.getAll().entrySet())if(x.getKey().startsWith(prefix)&&x.getValue() instanceof Integer)m.put(x.getKey().substring(prefix.length()),(Integer)x.getValue());for(MediaEntry e:recent()){String t="episode".equals(e.type)?"series":e.type;if(type.equals(t)&&e.categoryId!=null&&!e.categoryId.isEmpty())m.put(e.categoryId,m.getOrDefault(e.categoryId,0)+4);}for(MediaEntry e:favorites()){String t="episode".equals(e.type)?"series":e.type;if(type.equals(t)&&e.categoryId!=null&&!e.categoryId.isEmpty())m.put(e.categoryId,m.getOrDefault(e.categoryId,0)+6);}String best="";int score=-1;for(Map.Entry<String,Integer>x:m.entrySet())if(x.getValue()>score){score=x.getValue();best=x.getKey();}return best;}
    public void saveProgress(MediaEntry e,long position,long duration){saveProgress(e,position,duration,false);}
    public void saveProgress(MediaEntry e,long position,long duration,boolean durable){
        if(e==null||"live".equals(e.type)||position<0)return;
        String k=StoredMediaKey.of(e);SharedPreferences.Editor ed=p.edit();
        if(duration>0&&position>=duration*0.95){ed.putBoolean("watched:"+k,true).remove("progress:"+k);if(duration>0)ed.putLong("duration:"+k,duration);}
        else if(position>10000){ed.putLong("progress:"+k,position).putBoolean("watched:"+k,false);if(duration>0)ed.putLong("duration:"+k,duration);}
        else return;
        ed.putLong("progress_updated:"+k,System.currentTimeMillis());cache(e);
        if(durable){if(!ed.commit())throw new IllegalStateException("PROGRESS_SAVE_FAILED");}else ed.apply();
    }
    public void markWatched(MediaEntry e){if(e==null||"live".equals(e.type))return;cache(e);if(!p.edit().putBoolean("watched:"+StoredMediaKey.of(e),true).putLong("progress_updated:"+StoredMediaKey.of(e),System.currentTimeMillis()).remove("progress:"+StoredMediaKey.of(e)).commit())throw new IllegalStateException("PROGRESS_SAVE_FAILED");}
    public boolean watched(MediaEntry e){return e!=null&&p.getBoolean("watched:"+StoredMediaKey.of(e),false);}
    public long progressUpdatedAt(MediaEntry e){return e==null?0:p.getLong("progress_updated:"+StoredMediaKey.of(e),0);}
    public void clearProgress(MediaEntry e){if(e==null)return;if(!p.edit().remove("progress:"+StoredMediaKey.of(e)).remove("duration:"+StoredMediaKey.of(e)).remove("watched:"+StoredMediaKey.of(e)).remove("progress_updated:"+StoredMediaKey.of(e)).commit())throw new IllegalStateException("PROGRESS_SAVE_FAILED");}
    public long progress(MediaEntry e){return e==null?0:p.getLong("progress:"+StoredMediaKey.of(e),0);}
    public long duration(MediaEntry e){return e==null?0:p.getLong("duration:"+StoredMediaKey.of(e),0);}
    public int progressPercent(MediaEntry e){if(watched(e))return 100;long d=duration(e),q=progress(e);return d>0?(int)Math.max(0,Math.min(100,q*100L/d)):0;}
    public List<MediaEntry> favorites(){List<MediaEntry>o=new ArrayList<>();for(String k:p.getStringSet("favorites",Collections.emptySet())){MediaEntry e=read(k);if(e!=null)o.add(e);}o.sort(Comparator.comparing(a->a.name==null?"":a.name,String.CASE_INSENSITIVE_ORDER));return o;}
    public List<MediaEntry> favorites(String type){List<MediaEntry>o=new ArrayList<>();for(MediaEntry e:favorites()){String t="episode".equals(e.type)?"series":e.type;if(type.equals(t))o.add(e);}return o;}
    public List<MediaEntry> recent(){List<MediaEntry>o=new ArrayList<>();try{JSONArray a=new JSONArray(p.getString("recent","[]"));for(int i=0;i<a.length();i++){MediaEntry e=read(a.optString(i));if(e!=null)o.add(e);}}catch(Exception ignored){}return o;}
    public List<MediaEntry> recent(String type){List<MediaEntry>o=new ArrayList<>();for(MediaEntry e:recent()){String t="episode".equals(e.type)?"series":e.type;if(type.equals(t))o.add(e);}return o;}
    public List<MediaEntry> continueWatching(String type){List<MediaEntry>o=new ArrayList<>();for(MediaEntry e:recent()){String t="episode".equals(e.type)?"series":e.type;if(type.equals(t)&&progress(e)>0)o.add(e);if(o.size()>=20)break;}return o;}
    public List<MediaEntry> continueWatching(){List<MediaEntry>o=new ArrayList<>();for(MediaEntry e:recent())if(!"live".equals(e.type)&&progress(e)>0){o.add(e);if(o.size()>=20)break;}return o;}
    public int recentRank(MediaEntry e){if(e==null)return Integer.MAX_VALUE;List<MediaEntry>r=recent();for(int i=0;i<r.size();i++)if(r.get(i).uniqueKey().equals(e.uniqueKey()))return i;return Integer.MAX_VALUE;}
    private void cache(MediaEntry e){try{JSONObject x=new JSONObject();x.put("id",e.id);x.put("streamId",e.streamId);x.put("seriesId",e.seriesId);x.put("name",e.name);x.put("type",e.type);x.put("url",e.url);x.put("directSource",e.directSource);x.put("sourceId",e.sourceId);x.put("sourceName",e.sourceName);x.put("catchup",e.catchup);x.put("catchupDays",e.catchupDays);x.put("catchupType",e.catchupType);x.put("catchupSource",e.catchupSource);x.put("group",e.group);x.put("categoryId",e.categoryId);x.put("tvgId",e.tvgId);x.put("tvgName",e.tvgName);x.put("year",e.year);x.put("rating",e.rating);x.put("plot",e.plot);x.put("extension",e.extension);x.put("seriesTitle",e.seriesTitle);x.put("season",e.season);x.put("episode",e.episode);x.put("tmdb",e.tmdbId);x.put("imdb",e.imdbId);x.put("logo",e.logo);x.put("backdrop",e.backdrop);x.put("candidates",new JSONArray(e.candidates));p.edit().putString("item:"+StoredMediaKey.of(e),crypto.encrypt(x.toString())).apply();}catch(Exception ignored){}}
    private MediaEntry read(String key){try{String raw=crypto.decrypt(p.getString("item:"+key,""));if(raw.isEmpty())return null;JSONObject x=new JSONObject(raw);MediaEntry e=new MediaEntry();e.id=x.optString("id");e.streamId=x.optString("streamId");e.seriesId=x.optString("seriesId");e.name=x.optString("name","Untitled");e.type=x.optString("type","live");e.url=x.optString("url");e.directSource=x.optString("directSource");e.sourceId=x.optString("sourceId");e.sourceName=x.optString("sourceName");e.catchup=x.optBoolean("catchup",false);e.catchupDays=x.optInt("catchupDays",0);e.catchupType=x.optString("catchupType","");e.catchupSource=x.optString("catchupSource","");e.group=x.optString("group");e.categoryId=x.optString("categoryId");e.tvgId=x.optString("tvgId");e.tvgName=x.optString("tvgName");e.year=x.optString("year");e.rating=x.optString("rating");e.plot=x.optString("plot");e.extension=x.optString("extension");e.seriesTitle=x.optString("seriesTitle");e.season=x.optInt("season");e.episode=x.optInt("episode");e.tmdbId=x.optString("tmdb");e.imdbId=x.optString("imdb");e.logo=x.optString("logo");e.backdrop=x.optString("backdrop");JSONArray a=x.optJSONArray("candidates");if(a!=null)for(int i=0;i<a.length();i++)e.candidates.add(a.optString(i));return e;}catch(Exception e){return null;}}
}

