plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nenotv.admin'
    compileSdk 36

    defaultConfig {
        applicationId 'com.nenotv.admin'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
