package com.nenotv.player;
public final class DemoSource {
public static final String URL="nenotv://demo/v1";
public static final int LIVE_COUNT=0;
public static final int FILM_COUNT=3;
public static final String PLAYLIST="#EXTM3U\n#EXTINF:-1 tvg-id=\"film-46670912\" tvg-logo=\"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/Caminandes%2C_Gran_Dillama_-_Blender_Foundation.webm/500px--Caminandes%2C_Gran_Dillama_-_Blender_Foundation.webm.jpg\" group-title=\"Open films\",Caminandes: Gran Dillama\nhttps://upload.wikimedia.org/wikipedia/commons/transcoded/8/8b/Caminandes%2C_Gran_Dillama_-_Blender_Foundation.webm/Caminandes%2C_Gran_Dillama_-_Blender_Foundation.webm.480p.vp9.webm\n#EXTINF:-1 tvg-id=\"film-29654117\" tvg-logo=\"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Caminandes-_Llama_Drama_-_Short_Movie.ogv/500px--Caminandes-_Llama_Drama_-_Short_Movie.ogv.jpg\" group-title=\"Open films\",Caminandes: Llama Drama\nhttps://upload.wikimedia.org/wikipedia/commons/transcoded/d/d0/Caminandes-_Llama_Drama_-_Short_Movie.ogv/Caminandes-_Llama_Drama_-_Short_Movie.ogv.480p.vp9.webm\n#EXTINF:-1 tvg-id=\"film-52325031\" tvg-logo=\"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Caminandes_3_-_Llamigos_-_Blender_Animated_Short.webm/500px--Caminandes_3_-_Llamigos_-_Blender_Animated_Short.webm.jpg\" group-title=\"Open films\",Caminandes 3 - Llamigos\nhttps://upload.wikimedia.org/wikipedia/commons/transcoded/a/ab/Caminandes_3_-_Llamigos_-_Blender_Animated_Short.webm/Caminandes_3_-_Llamigos_-_Blender_Animated_Short.webm.480p.vp9.webm\n";
public static void decorate(com.nenotv.player.model.MediaEntry e){if("film-46670912".equals(e.tvgId)){e.type="vod";e.year="2013";e.plot="Blender Foundation | CC BY-SA 3.0 | https://creativecommons.org/licenses/by-sa/3.0 | Source: https://commons.wikimedia.org/wiki/File:Caminandes,_Gran_Dillama_-_Blender_Foundation.webm | Unmodified film/official live feed.";return;}if("film-29654117".equals(e.tvgId)){e.type="vod";e.year="2013";e.plot="Pablo Vazquez, Beorn Leonard, and Francesco Siddi. Music and Sound by Jan Morgenstern | CC BY 3.0 | https://creativecommons.org/licenses/by/3.0 | Source: https://commons.wikimedia.org/wiki/File:Caminandes-_Llama_Drama_-_Short_Movie.ogv | Unmodified film/official live feed.";return;}if("film-52325031".equals(e.tvgId)){e.type="vod";e.year="2016";e.plot="Blender | CC BY 3.0 | https://creativecommons.org/licenses/by/3.0 | Source: https://commons.wikimedia.org/wiki/File:Caminandes_3_-_Llamigos_-_Blender_Animated_Short.webm | Unmodified film/official live feed.";return;}}
public static boolean isEntry(com.nenotv.player.model.MediaEntry e){return e!=null&&e.url!=null&&PLAYLIST.contains("\n"+e.url+"\n");}
public static androidx.media3.exoplayer.source.DefaultMediaSourceFactory mediaSourceFactory(android.content.Context c, com.nenotv.player.model.MediaEntry e){androidx.media3.exoplayer.source.DefaultMediaSourceFactory factory=new androidx.media3.exoplayer.source.DefaultMediaSourceFactory(c);if(isEntry(e)){androidx.media3.datasource.DefaultHttpDataSource.Factory http=new androidx.media3.datasource.DefaultHttpDataSource.Factory().setUserAgent("SunnyIPTV/0.13.11 (https://sunnyiptv.com; info@sunnyiptv.com) Android Media3");factory.setDataSourceFactory(new androidx.media3.datasource.DefaultDataSource.Factory(c,http));factory.setLoadErrorHandlingPolicy(new androidx.media3.exoplayer.upstream.DefaultLoadErrorHandlingPolicy(6){@Override public long getRetryDelayMsFor(androidx.media3.exoplayer.upstream.LoadErrorHandlingPolicy.LoadErrorInfo info){Throwable cause=info.exception;while(cause!=null){if(cause instanceof androidx.media3.datasource.HttpDataSource.InvalidResponseCodeException){int status=((androidx.media3.datasource.HttpDataSource.InvalidResponseCodeException)cause).responseCode;if(status==429||status==503)return 15000L*Math.min(info.errorCount,4);}cause=cause.getCause();}return super.getRetryDelayMsFor(info);}});}return factory;}
private DemoSource(){}
}
