package com.nenotv.player;
import android.app.*;import android.os.*;import android.graphics.Typeface;import android.text.InputType;import android.view.*;import android.widget.*;
import com.nenotv.player.storage.*;
public class SettingsActivity extends Activity{
  LinearLayout box; android.content.SharedPreferences p; String langAtOpen;
  int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
  String T(String k){return UiText.t(this,k);} 
  TextView t(String x,int z){TextView v=new TextView(this);v.setText(x);v.setTextColor(0xFFF7F8FA);v.setTextSize(z);return v;}
  Button b(String x){Button v=new Button(this);v.setText(x);v.setAllCaps(false);v.setTextColor(0xFFF7F8FA);v.setBackgroundTintList(android.content.res.ColorStateList.valueOf(0xFF1B2028));return v;}
  @Override public void onCreate(Bundle x){super.onCreate(x);SettingsStore.migrateLanguagePreferences(this);p=SettingsStore.prefs(this);langAtOpen=SettingsStore.language(this);build();UiText.applyDirection(this);}
  void build(){ScrollView sv=new ScrollView(this);sv.setBackgroundColor(0xFF07090D);sv.setClipToPadding(true);sv.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(0,insets.getSystemWindowInsetTop(),0,insets.getSystemWindowInsetBottom());return insets;});sv.requestApplyInsets();box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(12),dp(18),dp(30));sv.addView(box);
    LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView title=t(T("settings"),28);title.setTypeface(null,Typeface.BOLD);h.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button close=b(T("close"));close.setOnClickListener(v->finish());h.addView(close);box.addView(h);
    sec(T("language"));spin(T("app_language"),"language",appLanguageLabels(),new String[]{"nl","en","de","fr","es","it","pt","tr","pl","ar"});TextView langHelp=t(T("language_help")+" "+T("content_language_help"),12);langHelp.setTextColor(0xFF8D96A4);langHelp.setPadding(0,0,0,dp(8));box.addView(langHelp);
    sec(T("general"));toggle(T("compact"),"compact",true);spin(T("hero_size"),"hero_size",new String[]{T("small"),T("normal"),T("large")},new String[]{"small","normal","large"});spin(T("start_screen"),"start_screen",new String[]{T("home"),T("last_tab"),T("live_tv"),T("epg"),T("movies"),T("series")},new String[]{"home","last","live","epg","vod","series"});spin(T("default_sort"),"sort",new String[]{T("provider"),"A–Z","Z–A",T("favorites_first"),T("recent_first")},new String[]{"provider","az","za","favorites","recent"});
    sec("🔒 PRO · "+T("parental_controls"));Switch parental=new Switch(this);parental.setText("🔒 "+T("hide_adult"));parental.setTextColor(0xFFF7F8FA);parental.setChecked(SettingsStore.parental(this));parental.setOnCheckedChangeListener((v,on)->{if(on&&!ProGate.require(this,T("parental_controls"))){v.setChecked(false);return;}if(on&&!SettingsStore.hasParentalPin(this)){askNewPin(ok->{if(ok){SettingsStore.setParentalEnabled(this,true);}else{v.setChecked(false);}});}else SettingsStore.setParentalEnabled(this,on);});box.addView(parental,new LinearLayout.LayoutParams(-1,dp(52)));Button pin=b(SettingsStore.hasParentalPin(this)?T("pin_change"):T("pin_set"));pin.setOnClickListener(v->askNewPin(ok->{if(ok){pin.setText(T("pin_change"));Toast.makeText(this,T("pin_saved"),Toast.LENGTH_SHORT).show();}}));box.addView(pin,new LinearLayout.LayoutParams(-1,dp(50)));Button unlock=b(SettingsStore.adultsAllowed(this)?T("adult_unlocked"):T("adult_unlock"));unlock.setOnClickListener(v->{if(!SettingsStore.parental(this)){Toast.makeText(this,T("parental_off"),Toast.LENGTH_SHORT).show();return;}askUnlock(ok->{if(ok){unlock.setText(T("adult_unlocked"));Toast.makeText(this,T("unlocked_until_close"),Toast.LENGTH_SHORT).show();}});});box.addView(unlock,new LinearLayout.LayoutParams(-1,dp(50)));
    sec(T("playback"));TextView proHint=t("🔒 PRO · "+T("picture_in_picture")+" · "+T("advanced_subtitles"),12);proHint.setTextColor(0xFFFFD400);box.addView(proHint);spin(T("player"),"player",new String[]{T("automatic"),"VLC","Media3"},new String[]{"auto","vlc","media3"});spin(T("buffer"),"buffer",new String[]{T("fast"),T("stable"),T("maximum")},new String[]{"normal","stable","max"});spin(T("audio_pref"),"audio",audioLanguageLabels(),new String[]{"auto","original","nl","en","de","fr","es","it","pt","tr","pl","ar"});spin(T("subtitle_pref"),"subtitles",subtitleLanguageLabels(),new String[]{"auto","off","nl","en","de","fr","es","it","pt","tr","pl","ar"});toggle(T("picture_in_picture"),"pip",true);toggle(T("autoplay"),"autoplay_next",true);
    sec(T("advanced_subtitles"));Button bridge=b(T("external_subtitle_bridge"));bridge.setOnClickListener(v->editSubtitleBridge());box.addView(bridge,new LinearLayout.LayoutParams(-1,dp(50)));
    sec(T("maintenance"));Button re=b(T("reindex"));re.setOnClickListener(v->{p.edit().putBoolean("force_reindex",true).apply();Toast.makeText(this,T("reindex_started"),Toast.LENGTH_SHORT).show();});box.addView(re,new LinearLayout.LayoutParams(-1,dp(50)));Button cl=b(T("clear_cache"));cl.setOnClickListener(v->{MediaRowAdapter.clearArtworkCache();MainActivity.clearHeroCache();Toast.makeText(this,T("cache_cleared"),Toast.LENGTH_SHORT).show();});box.addView(cl,new LinearLayout.LayoutParams(-1,dp(50)));
    sec(T("library"));SecureProfileStore profiles=new SecureProfileStore(this);if(profiles.exists()){com.nenotv.player.model.Profile profile=profiles.load();String base=profile.type.name()+"|"+profile.server+"|"+profile.username+"|"+profile.m3uUrl;String key=Integer.toHexString(base.hashCode())+":"+profile.type.name();SearchIndexStore index=new SearchIndexStore(this);TextView stats=t(T("live_tv")+": "+index.countSection(key,"live")+"\n"+T("movies")+": "+index.countSection(key,"vod")+"\n"+T("series")+": "+index.countSection(key,"series"),13);box.addView(stats);index.close();}sec(T("about"));TextView a=t("SunnyIPTV "+BuildConfig.VERSION_NAME+"\nLight + Pro",13);a.setTextColor(0xFFA7AFBC);box.addView(a);setContentView(sv);}
  void editSubtitleBridge(){SecureProfileStore store=new SecureProfileStore(this);if(!store.exists()){Toast.makeText(this,T("profile_required"),Toast.LENGTH_SHORT).show();return;}com.nenotv.player.model.Profile profile=store.load();LinearLayout wrap=new LinearLayout(this);wrap.setOrientation(LinearLayout.VERTICAL);wrap.setPadding(dp(18),0,dp(18),0);EditText url=new EditText(this);url.setHint(T("bridge_url"));url.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);url.setText(profile.bridgeUrl);EditText token=new EditText(this);token.setHint(T("bridge_token_optional"));token.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);token.setText(profile.bridgeToken);wrap.addView(url);wrap.addView(token);new AlertDialog.Builder(this).setTitle(T("external_subtitle_bridge")).setMessage(T("bridge_help")).setView(wrap).setNegativeButton(T("cancel"),null).setPositiveButton(T("save"),(d,w)->{profile.bridgeUrl=url.getText().toString().trim();profile.bridgeToken=token.getText().toString();store.save(profile);Toast.makeText(this,T("saved"),Toast.LENGTH_SHORT).show();}).show();}
  String languageName(String code){return SettingsStore.displayLanguage(this,code);}
  String[] appLanguageLabels(){return new String[]{languageName("nl"),languageName("en"),languageName("de"),languageName("fr"),languageName("es"),languageName("it"),languageName("pt"),languageName("tr"),languageName("pl"),languageName("ar")};}
  String[] contentLanguageLabels(){return new String[]{T("follow_app_language"),languageName("nl"),languageName("en"),languageName("de"),languageName("fr"),languageName("es"),languageName("it"),languageName("pt"),languageName("tr"),languageName("pl"),languageName("ar")};}
  String[] audioLanguageLabels(){return new String[]{T("follow_app_language"),T("original"),languageName("nl"),languageName("en"),languageName("de"),languageName("fr"),languageName("es"),languageName("it"),languageName("pt"),languageName("tr"),languageName("pl"),languageName("ar")};}
  String[] subtitleLanguageLabels(){return new String[]{T("follow_app_language"),T("off"),languageName("nl"),languageName("en"),languageName("de"),languageName("fr"),languageName("es"),languageName("it"),languageName("pt"),languageName("tr"),languageName("pl"),languageName("ar")};}
  interface Done{void ok(boolean ok);}
  void askNewPin(Done done){EditText e=new EditText(this);e.setHint(T("pin_digits"));e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);e.setTextColor(0xFFF7F8FA);e.setHintTextColor(0xFF8D96A4);AlertDialog a=new AlertDialog.Builder(this).setTitle(T("parental_pin")).setMessage(T("pin_help")).setView(e).setNegativeButton(T("cancel"),(d,w)->done.ok(false)).setPositiveButton(T("save"),null).create();a.setOnShowListener(d->a.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String pin=e.getText().toString().trim();if(pin.length()<4||pin.length()>8){e.setError(T("pin_digits"));return;}SettingsStore.setParentalPin(this,pin);a.dismiss();done.ok(true);}));a.show();}
  void askUnlock(Done done){EditText e=new EditText(this);e.setHint("PIN");e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);e.setTextColor(0xFFF7F8FA);AlertDialog a=new AlertDialog.Builder(this).setTitle(T("adult_unlock")).setView(e).setNegativeButton(T("cancel"),(d,w)->done.ok(false)).setPositiveButton(T("unlock"),null).create();a.setOnShowListener(d->a.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(SettingsStore.unlockAdults(this,e.getText().toString().trim())){a.dismiss();done.ok(true);}else e.setError(T("wrong_pin"));}));a.show();}
  void sec(String x){TextView v=t(x,18);v.setTypeface(null,Typeface.BOLD);v.setPadding(0,dp(20),0,dp(7));box.addView(v);}
  void toggle(String l,String k,boolean d){Switch v=new Switch(this);v.setText(l);v.setTextColor(0xFFF7F8FA);v.setChecked(p.getBoolean(k,d));v.setOnCheckedChangeListener((a,on)->p.edit().putBoolean(k,on).apply());box.addView(v,new LinearLayout.LayoutParams(-1,dp(52)));}
  void spin(String l,String k,String[]ls,String[]vs){TextView z=t(l,13);z.setTextColor(0xFFA7AFBC);box.addView(z);Spinner sp=new Spinner(this);ArrayAdapter<String>ad=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,ls){@Override public View getDropDownView(int q,View v,ViewGroup g){TextView x=(TextView)super.getDropDownView(q,v,g);x.setTextColor(0xFFF7F8FA);x.setBackgroundColor(0xFF181C22);x.setPadding(dp(16),dp(14),dp(16),dp(14));return x;}};ad.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);sp.setAdapter(ad);String cur=p.getString(k,vs[0]);int n=0;for(int i=0;i<vs.length;i++)if(vs[i].equals(cur))n=i;sp.setSelection(n,false);final boolean[] ready={false};sp.post(()->ready[0]=true);sp.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>x){}public void onItemSelected(AdapterView<?>x,View v,int q,long id){if(!ready[0])return;String next=vs[q];String old=p.getString(k,vs[0]);if(next.equals(old))return;if("language".equals(k)){SettingsStore.setPrimaryLanguage(SettingsActivity.this,next);recreate();}else p.edit().putString(k,next).apply();}});box.addView(sp,new LinearLayout.LayoutParams(-1,dp(48)));}
}
